config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#                   events GET    /events(.:format)              events#index
#                          POST   /events(.:format)              events#create
#                new_event GET    /events/new(.:format)          events#new
#               edit_event GET    /events/:id/edit(.:format)     events#edit
#                    event PATCH  /events/:id(.:format)          events#update
#                          PUT    /events/:id(.:format)          events#update
#                          DELETE /events/:id(.:format)          events#destroy
#               statistics GET    /statistics(.:format)          statistics#index
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create
#                     root GET    /                              events#index

Rails.application.routes.draw do
  resources :events, except: [:show]

  get 'statistics', to: 'statistics#index', as: 'statistics'
  devise_for :users

  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id          :bigint(8)        not null, primary key
#  user_id     :bigint(8)
#  title       :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  intensity   :integer          not null
#  start       :date
#  end         :date
#
# Indexes
#
#  index_events_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Event < ApplicationRecord
  # enum intensity: %i[very_weak weak normal strong very_strong]
  belongs_to :user, inverse_of: :events

  after_initialize :set_default_values, only: :new_record?

  validates :title, presence: true
  validates :start_time, presence: true
  validates :intensity, presence: true

  private

  def set_default_values
    self.title = I18n.t 'menka.event.default_title'
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.order(:start_time)
    @last_event = @events.last
  end

  # GET /events/1
  # GET /events/1.json
  def show
    redirect_to events_path if @event.blank?
  end

  # GET /events/new
  def new
    start_time = params[:start_time] || Time.zone.now
    @event = current_user.events.build(start_time: start_time)
  end

  # GET /events/1/edit
  def edit
    redirect_to events_path if @event.blank?
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    redirect_to events_path if @event.blank?

    if params[:end] == 'today'
      @event.end_time = Time.zone.now
      respond_to do |format|
        if @event.save
          format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        end
      end
    else
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    redirect_to events_path if @event.blank?

    respond_to do |format|
      if @event.user_id == current_user.id
        @event.destroy
        format.html { redirect_to events_path, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to events_path, notice: 'Event was not destroyed.' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = current_user.events.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:start_time, :intensity, :end_time, :title, :analyse, :description)
  end
end

app/helpers/event_helper.rb
# frozen_string_literal: true

module EventHelper
  def days_diff(from, to)
    ((from - to) / 60 / 60 / 24).round.abs
  end
end

module SimpleCalendar
  class Calendar
    def bulma_classes_for(day)
      # today = Date.current

      bulma_class = ['datepicker-date']
      # bulma_class << 'is-today'                if today == day
      bulma_class << 'is-current-month'        if start_date.month == day.month
      bulma_class << 'datepicker-range'        if sorted_events.fetch(day, []).any?
      bulma_class << 'datepicker-range-start'  if day.to_date == sorted_events.fetch(day, []).pluck(:start_time).map(&:to_date).uniq[0]
      bulma_class << 'datepicker-range-end' if sorted_events.fetch(day, []).pluck(:end_time).uniq.any? && day.to_date == sorted_events.fetch(day, []).pluck(:end_time).map(&:to_date).uniq[0]
      # bulma_class << 'prev-month'    if start_date.month != day.month && day < start_date
      # bulma_class << 'next-month'    if start_date.month != day.month && day > start_date
      # bulma_class << "wday-#{day.wday.to_s}"
      # bulma_class << 'past'          if today > day
      # bulma_class << 'future'        if today < day
      bulma_class
    end
  end
end

app/views/events/_event.html.haml
%tr
  %td
    - if event.start_time.present?
      = event.start_time.strftime(t('time.formats.default'))
  %td
    - if event.end_time.present?
      = event.end_time.strftime(t('time.formats.default'))
  %td{colspan: 3}
    .field.is-grouped
      = link_to edit_event_path(event) do
        %span.icon
          %i.fas.fa-edit.fa-lg
      = link_to event, method: :delete, remote: true do
        %span.icon
          %i.fas.fa-trash.fa-lg
      - if event.end_time.blank?
        = link_to event_path(event, end: :today), remote: true, method: :patch do
          %span.icon
            %i.fas.fa-calendar-check.fa-lg

app/views/events/_form.html.haml
= form_for event do |f|
  .field.is-horizontal
    .field-body
      .field
        = f.label :start_time, class: 'label'
        .control.has-icons-left.is-expanded
          = f.date_field :start_time, class: 'input is-large', required: true
          %span.icon.is-small.is-left
            %i.fas.fa-calendar

      .field
        = f.label :end_time, class: 'label'
        .control.has-icons-left.is-expanded
          = f.date_field :end_time, class: 'input is-large', min: f.object.start_time || Time.zone.now
          %span.icon.is-small.is-left
            %i.fas.fa-calendar
  .field
    = f.label :title, class: 'label'
    .control
      = f.text_field :title, class: 'input is-large', required: true
  .field
    .control
      = f.label :intensity, class: 'label'
      = f.range_field :intensity, in: 0..4, class: 'slider is-large is-danger has-output is-fullwidth', required: true
      %output{for: 'event_intensity'}
        = f.object.intensity || 2
  .field
    = f.check_box :analyse, class: 'switch is-info'
    = f.label :analyse
  .field
    = f.label :description, class: 'label'
    .control
      = f.text_area :description, class: 'textarea'
  .field
    .control
      = f.submit "Submit", class: 'button is-primary is-fullwidth'

app/views/events/edit.html.haml
.section
  .container.is-fullhd
    .card
      %header.card-header
        %p.card-header-title
          = t('menka.strings.edit')
        = link_to :back, class: 'card-header-icon' do
          %span.icon
            %i.fas.fa-times
      .card-content
        .content
          = render 'form', event: @event

app/views/events/index.html.haml
.section
  .container
    .tile.is-ancestor
      .tile.is-vertical
        - if @events.size > 0
          .tile.is-parent.is-vertical
            %p.tile.is-child.notification.is-grey-light
              - if @last_event.end_time
                = "#{days_diff Time.zone.now, @last_event.end_time} days since last event"
              - else
                = "#{days_diff Time.zone.now, @last_event.start_time} days since beginning"
        .tile.is-parent
          .tile.is-12.is-child.box.has-shadow
            = link_to new_event_path, class: "button is-fullwidth" do
              %span.icon
                %i.fas.fa-lg.fa-calendar-plus
              %span
                = t('menka.event.new')
            %hr.divider
            = month_calendar events: @events  do |date, events|
              = link_to new_event_path({start_time: date}), type: 'button', class: "button date-item #{"is-today" if Time.zone.now.to_date == date}" do
                = date.day
      .tile.is-parent
        .tile.is-child.box.has-shadow
          %table.table.is-fullwidth
            %thead
              %tr
                %th{colspan: 3}
                  Overview
            %tbody
              = render @events

app/views/events/new.html.haml
.section
  .container.is-fullhd
    .card
      %header.card-header
        %p.card-header-title
          = t('menka.strings.new')
        = link_to :back, class: 'card-header-icon' do
          %span.icon
            %i.fas.fa-times
      .card-content
        .content
          = render 'form', event: @event