config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#                   events GET    /events(.:format)              events#index
#                          POST   /events(.:format)              events#create
#                new_event GET    /events/new(.:format)          events#new
#               edit_event GET    /events/:id/edit(.:format)     events#edit
#                    event PATCH  /events/:id(.:format)          events#update
#                          PUT    /events/:id(.:format)          events#update
#                          DELETE /events/:id(.:format)          events#destroy
#               statistics GET    /statistics(.:format)          statistics#index
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#            user_password PATCH  /users/password(.:format)      devise/passwords#update
#                          PUT    /users/password(.:format)      devise/passwords#update
#                          POST   /users/password(.:format)      devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#        user_registration PATCH  /users(.:format)               devise/registrations#update
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
#                          POST   /users(.:format)               devise/registrations#create
#                     root GET    /                              events#index

Rails.application.routes.draw do
  resources :events, except: [:show]

  get 'statistics', to: 'statistics#index', as: 'statistics'
  devise_for :users

  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.haml
%nav.navbar.is-fixed-top.is-dark{"aria-label" => "main navigation", :role => "navigation"}
  .container.is-fluid
    .navbar-brand
      = link_to root_path, class: 'navbar-item' do
        %span.icon
          %i.fas.fa-heart
        %span
          = t('menka.app_title')
      %a.navbar-burger.burger{"aria-expanded" => "false", "aria-label" => "menu", "data-target" => "navbarMain", :role => "button"}
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}
    #navbarMain.navbar-menu
      .navbar-start
        = link_to events_path, class: 'navbar-item' do
          = t('menka.nav.events')
        = link_to statistics_path, class: 'navbar-item' do
          = t('menka.nav.statistics')
      .navbar-end
        .navbar-item.has-dropdown.is-hoverable
          %a.navbar-link
            = current_user.nickname
          .navbar-dropdown.is-right
            = link_to t('menka.profile'),  edit_user_registration_path, class: "navbar-item"
            %hr.navbar-divider/
            = link_to t('menka.sign_out'),  destroy_user_session_path, method: :delete, class: "navbar-item"

app/views/layouts/application.html.haml
!!!
%html.has-background-grey-light{class: "#{'has-navbar-fixed-top' if user_signed_in?}"}
  %head
    %meta{content: 'IE=edge, chrome=1', 'http-equiv': 'X-UA-Compatible'}/
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %meta{name: "viewport", content:"width=device-width, initial-scale=1"}
    %title
      = t('menka.app_title')
    = csrf_meta_tags
    = stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload', media: 'all'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if user_signed_in?
      = render 'layouts/navigation'
    = yield